ALTER TABLE `payouts`
  ADD COLUMN `requestedAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN `gatewayFeeAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN `gatewayFeeRate` DECIMAL(10,6) NULL,
  ADD COLUMN `fixedFeeAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN `systemFeeAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN `systemFeeRate` DECIMAL(10,6) NULL,
  ADD COLUMN `totalDebitAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN `payoutAmount` DECIMAL(18,2) NOT NULL DEFAULT 0;
