CREATE TABLE IF NOT EXISTS `platform_withdrawals` (
  `id` VARCHAR(191) NOT NULL,
  `initiatedBy` VARCHAR(191) NOT NULL,
  `approvedBy` VARCHAR(191) NULL,
  `amount` DOUBLE NOT NULL,
  `fee` DOUBLE NOT NULL,
  `gatewayFeeAmount` DOUBLE NOT NULL DEFAULT 0,
  `gatewayFeeRate` DOUBLE NULL,
  `bankFixedFeeAmount` DOUBLE NOT NULL DEFAULT 0,
  `netAmount` DOUBLE NOT NULL,
  `payoutAmount` DOUBLE NOT NULL DEFAULT 0,
  `method` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'pending',
  `mobileOperator` VARCHAR(191) NULL,
  `mobileNumber` VARCHAR(191) NULL,
  `bankCode` VARCHAR(191) NULL,
  `accountName` VARCHAR(191) NULL,
  `accountNumber` VARCHAR(191) NULL,
  `chargeId` VARCHAR(191) NULL,
  `gatewayPayload` LONGTEXT NULL,
  `gatewayResponse` LONGTEXT NULL,
  `failureReason` TEXT NULL,
  `processedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `platform_withdrawals_chargeId_key`(`chargeId`),
  INDEX `platform_withdrawals_initiatedBy_idx`(`initiatedBy`),
  INDEX `platform_withdrawals_status_idx`(`status`),
  INDEX `platform_withdrawals_createdAt_idx`(`createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `platform_withdrawal_otps` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `otpHash` VARCHAR(191) NOT NULL,
  `payloadHash` VARCHAR(191) NOT NULL,
  `expiresAt` DATETIME(3) NOT NULL,
  `usedAt` DATETIME(3) NULL,
  `attempts` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `platform_withdrawal_otps_userId_expiresAt_idx`(`userId`, `expiresAt`),
  INDEX `platform_withdrawal_otps_payloadHash_idx`(`payloadHash`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
